<head>
    <meta charset="UTF-8">
    <title>Job Descriptions</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name ="description" content = "Job description for Software and Website Designer">
    <meta name ="keyword" content= "Jobs, Software Developer, Website Desginer, Front-end, Back-end, Description ">
    <meta name = "author"  content ="Duc Toan">
    <link href="styles/style1.css" rel='stylesheet'>
</head>

<header>
    <div class="header-container">
        <img src="styles/images/image.logo.png" alt="Logo" class="logo">
        <div class="header-text">
            <h1>Tech Network Software Solutions</h1>
            <p>Advanced Software Development Company Hiring the Best Talent in the Industry</p>
        </div>
    </div>
</header>

<nav>
    <ul>
        <li><a href="index.php">Home</a></li>
        <li><a href="job.php">Job Description</a></li>
        <li><a href="apply.php">Apply</a></li>
        <li><a href="about.php">About Us</a></li>
        <li><a href="mailto:info@TechNetworkSoftwaresolutions.com.au">Contact Us</a></li>
    </ul>
</nav>