<!-- nav.inc -->
<nav>
  <ul>
    <li><a href="index.php">Home</a></li>
    <li><a href="job.php">Job Description</a></li>
    <li><a href="apply.php">Apply</a></li>
    <li><a href="about.php">About Us</a></li>
    <li><a href="mailto:info@TechNetworkSoftwaresolutions.com.au">Contact Us</a></li>
    <li><a href="manage.php">Manage EOIs</a></li>
    <li><a href="enhancement.php">Enhancements</a></li>
  </ul>
</nav>
